cooking_memory/cooking_memory/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cooking_memory/cooking_memory_app/login_view/accounts/urls.py
from django.urls import path
from .views import(
    PortfolioView,RegistUserView,
    UserLogoutView,UserLoginView2,
    UserLogoutView2,ChangeEmailView,MyPasswordChangeView,
    MyPageView,GenerateInviteView,InviteRegistUserView,
    ShareUsersView,UploadProfileImageView, ChangeUsernameView,
    
)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',PortfolioView.as_view(),name='portfolio'),
]

app_name='accounts'
urlpatterns = [
    path('regist/',RegistUserView.as_view(),name='regist'),
    path('user_logout/',UserLogoutView.as_view(),name='user_logout'),
    path('user_login2/',UserLoginView2.as_view(),name='user_login_2'),
    path('user_logout2/',UserLogoutView2.as_view(),name='user_logout_2'),
    path('change_email/',ChangeEmailView.as_view(),name='change_email'),
    path('change_password/',MyPasswordChangeView.as_view(),name='change_password'),
    path('mypage/', MyPageView.as_view(), name='mypage'),
    path('generate_invite/',GenerateInviteView.as_view(),name='generate_invite'),
    path('share_regist/<str:invitation_url>/', InviteRegistUserView.as_view(), name='share_regist'),
    path('share_users/', ShareUsersView.as_view(), name='share_users'),
    path('upload_profile_image/', UploadProfileImageView.as_view(), name='upload_profile_image'),
    path('change_username/', ChangeUsernameView.as_view(), name='change_username'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/cooking_records/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import(
    MyListView,CookingRecordCreateView,CreateCookingCategoryView,
    CreateToggleFavoriteView,CookingRecordDetailView,
    CookingRecordDeleteView,CookingRecordUpdateView,ToggleFavoriteView
)
from . import views

app_name='cooking_records'
urlpatterns = [
    path('my_list/',MyListView.as_view(),name='my_list'),
    path('create/', CookingRecordCreateView.as_view(), name='cooking_record_create'),
    path('create_category/', CreateCookingCategoryView.as_view(), name='create_cooking_category'),
    path('create_toggle_favorite/', CreateToggleFavoriteView.as_view(), name='create_toggle_favorite'),
    path('record_detail/<int:pk>/', CookingRecordDetailView.as_view(), name='record_detail'),
    path('cooking_record/<int:pk>/delete/', CookingRecordDeleteView.as_view(), name='cooking_record_delete'),
    path('<int:pk>/update/', CookingRecordUpdateView.as_view(), name='cooking_record_update'),
    path('<int:pk>/toggle_favorite/', ToggleFavoriteView.as_view(), name='toggle_favorite'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/login_view/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from login_view.views import PortfolioView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PortfolioView.as_view(), name='portfolio'),  # ← トップページに設定
    path('accounts/', include('accounts.urls')),
    path('cooking_records/', include('cooking_records.urls')),
    path('recipes/', include('recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/recipes/urls.py
from django.urls import path
from .views import RecipeListView,RecipeCreateView,RecipeDeleteView

app_name='recipes'
urlpatterns = [
    path('recipe_list/',RecipeListView.as_view(),name='recipe_list'),
    path('add_recipe/',RecipeCreateView.as_view(),name='add_recipe'),
    path('recipe/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),

]

cooking_memory/cooking_memory_app/login_view/cooking_records/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
import datetime
from recipes.models import Recipe

User=get_user_model()

class CookingCategory(models.Model):
    user = models.ForeignKey(
        User,on_delete=models.PROTECT,
        related_name='cooking_categories'
    )
    name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class CookingRecord(models.Model):
    EASINESS_CHOICES = [
        (0, '簡単'),
        (1, '普通'),
        (2, '手間がかかる'),
    ]
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    cooking_category = models.ForeignKey('CookingCategory', on_delete=models.SET_NULL, null=True, blank=True,verbose_name='カテゴリ')
    image_url = models.ImageField(upload_to='cooking_records/', blank=False, null=True)
    date = models.DateField(default=datetime.date.today,verbose_name='日付')
    cooking_easiness = models.IntegerField(choices=EASINESS_CHOICES,default=1,verbose_name='調理の手軽さ')
    is_favorite = models.IntegerField(default=0,verbose_name='お気に入り')#0:お気に入りではない,1:お気に入り
    memo = models.CharField(max_length=300,blank=True,verbose_name='メモ')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.date} の献立記録"
    
class CookingRecordRecipe(models.Model):
    cooking_record = models.ForeignKey(CookingRecord, on_delete=models.CASCADE, related_name='cooking_record_recipes')
    recipe = models.ForeignKey('recipes.Recipe', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

cooking_memory/cooking_memory_app/login_view/recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model
User=get_user_model()

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    recipe_url = models.URLField(max_length=300,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
  

cooking_memory/cooking_memory_app/login_view/cooking_records/forms.py
from django import forms
from .models import CookingRecord, CookingCategory

class CookingRecordForm(forms.ModelForm):
    class Meta:
        model = CookingRecord
        fields = ['date', 'cooking_category', 'image_url', 'cooking_easiness', 'memo']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'memo': forms.Textarea(attrs={'rows': 3}),
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user.share_group:
            self.fields['cooking_category'].queryset = CookingCategory.objects.filter(user__share_group=user.share_group)
        else:
            self.fields['cooking_category'].queryset = CookingCategory.objects.filter(user=user)

cooking_memory/cooking_memory_app/login_view/recipes/forms.py
from django import forms
from .models import Recipe

class RecipeForm(forms.ModelForm):
    recipe_url = forms.URLField(
        label='URL',
        required=True,
        error_messages={
            'invalid': '有効なURLを入力してください。',  # カスタムメッセージ
        },
        widget=forms.TextInput(attrs={'class': 'input-large'})
    )
    
    class Meta:
        model = Recipe
        fields = ['name', 'recipe_url']

cooking_memory/cooking_memory_app/login_view/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import(
    TemplateView,CreateView,FormView,View
)
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash,get_user_model
from .forms import RegistForm,UserLoginForm,UserLoginForm2,EmailChangeForm,PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib import messages
from django.utils.crypto import get_random_string
from .models import Invitation,ShareGroup,User
from django.http import JsonResponse,Http404
from django.views import View
from django.views.generic.edit import FormView

User = get_user_model()

class PortfolioView(TemplateView):
    template_name='portfolio.html'
    
class RegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm
    success_url = reverse_lazy('cooking_records:my_list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()

        # ここでログイン処理
        user = authenticate(self.request, email=user.email, password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            print("認証失敗")
            
        return super().form_valid(form)
    
class UserLoginView2(FormView):
    template_name='user_login_2.html'
    form_class=UserLoginForm2
    success_url = reverse_lazy('cooking_records:my_list')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(self.request, email=email, password=password)
        if user:
            login(self.request, user)
            return super().form_valid(form)
        else:
            messages.error(self.request, "メールアドレスまたはパスワードが正しくありません。")
            return self.form_invalid(form)
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        print('next: ', next_url)
        return next_url if next_url else self.success_url

class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'user_logout.html')

    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect('cooking_records:my_list')
    
class UserLogoutView2(LogoutView):
    next_page = reverse_lazy('cooking_records:my_list')
    http_method_names = ['get', 'post']
    template_name = 'user_logout.html'   
    
class ChangeEmailView(LoginRequiredMixin,FormView):
    template_name='change_email.html'
    form_class=EmailChangeForm
    success_url = reverse_lazy('accounts:mypage')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ←ここで渡す
        return kwargs
    
    def form_valid(self, form):
        user = self.request.user
        user.email = form.cleaned_data['new_email']
        user.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        print('next: ', next_url)
        return next_url if next_url else self.success_url

class MyPasswordChangeView(LoginRequiredMixin, FormView):
    template_name='change_password.html'
    form_class=PasswordChangeForm
    success_url = reverse_lazy('accounts:mypage')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ←ここで渡す
        return kwargs
    
    def form_valid(self, form):
        new_password = form.cleaned_data['new_password']
        user = self.request.user
        user.set_password(new_password)
        user.save()
        update_session_auth_hash(self.request, user)  # ← これでログアウトされないように！
        return super().form_valid(form)
    

class MyPageView(LoginRequiredMixin, TemplateView):
    template_name = 'mypage.html'
        
class GenerateInviteView(LoginRequiredMixin, TemplateView):
    template_name = 'generate_invite.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token = get_random_string(20)
        
        # フルURLはcontextに渡すだけ
        invite_url = self.request.build_absolute_uri(
            reverse('accounts:share_regist', args=[token])
        )
        
        # invitation_urlにはtokenだけ保存
        Invitation.objects.create(
            user=self.request.user,
            invitation_url=token,
            used=0  # 0: 未使用
        )
            
        context['invite_url'] = invite_url
        return context
    
class InviteRegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm
    success_url = reverse_lazy('cooking_records:my_list')

    def dispatch(self, request, *args, **kwargs):
        self.invitation_url = kwargs.get('invitation_url')  # 招待URLの取得
        try:
            self.invitation = Invitation.objects.get(invitation_url=self.invitation_url, used=0)
        except Invitation.DoesNotExist:
            raise Http404("この招待URLは無効か、すでに使用されています。")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        # 招待者を取得
        inviter = self.invitation.user
        # 招待者がshare_groupを持っていなければ作成
        if not inviter.share_group:
            group = ShareGroup.objects.create()
            inviter.share_group = group
            inviter.save()
        else:
            group = inviter.share_group

        # 招待されたユーザーにもグループを割り当て
        user.share_group = group
        user.is_active = True
        user.save()

        # 招待トークンを使用済みにする
        self.invitation.used = 1
        self.invitation.save()

        # ここでログイン処理
        user = authenticate(self.request, email=user.email, password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            print("認証失敗")
            
        return super().form_valid(form)

class ShareUsersView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            print("ログインユーザー：", request.user)
            print("ユーザーのグループ：", request.user.share_group)
            
            share_group = request.user.share_group
            
            if share_group is None:
                # 共有グループに属していなければ空リストを返す
                return JsonResponse({'users': []})
        
            users = User.objects.filter(share_group=share_group).exclude(id=request.user.id)
            
            print("共有中ユーザー：", users)
            
            data = {
                'users': [{'name': user.username} for user in users]
            }
        except Exception as e:
            print("エラー内容：", str(e))
            
            data = {
                'error': str(e)
            }

        return JsonResponse(data)
    
class UploadProfileImageView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        
        if 'image' in request.FILES:
            user.image_url = request.FILES['image']
            user.save()
        return redirect('accounts:mypage')
    
class ChangeUsernameView(LoginRequiredMixin, View):
    def post(self, request):
        new_username = request.POST.get('username')
        if new_username:
            request.user.username = new_username
            request.user.save()
        return redirect('accounts:mypage')

cooking_memory/cooking_memory_app/login_view/login_view/views.py
from django.views.generic import TemplateView


class PortfolioView(TemplateView):
    template_name='portfolio.html'
    

cooking_memory/cooking_memory_app/login_view/recipes/views.py
from django.views.generic import ListView,CreateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Recipe
from .forms import RecipeForm

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipe_list.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        
        if self.request.user.share_group:
            queryset = Recipe.objects.filter(user__share_group=self.request.user.share_group)
        else:
            queryset = Recipe.objects.filter(user=self.request.user)

        if query:
            queryset = queryset.filter(name__icontains=query)

        return queryset.order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context
    
class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/add_recipe.html'
    success_url = reverse_lazy('recipes:recipe_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)    

class RecipeDeleteView(DeleteView):
    model = Recipe
    template_name = 'recipe_delete.html'  # 使わないけど書く
    success_url = reverse_lazy('recipes:recipe_list')

cooking_memory/cooking_memory_app/login_view/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>cooking_memory</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <style>
        .navbar-custom {
            background-color: rgba(251, 217, 114, 1); /* 薄黄色 */
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000;
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .nav-link {
            color: black;
            font-size: 45px;
        }

    </style>
        
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'accounts:mypage' %}">マイページ</a>
            <a class="navbar-brand"href="{% url 'cooking_records:my_list' %}">マイリスト</a>
            <a class="navbar-brand"href="{% url 'recipes:recipe_list' %}">レシピリスト</a>
        </div>
    </nav>
              
    <form id="logout-form" method="POST" action="{% url 'accounts:user_logout_2' %}">
        {% csrf_token %}
    </form>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

cooking_memory/cooking_memory_app/login_view/templates/cooking_records_detail.html
{% extends 'base.html' %}
{% block content %}

{% for record in cooking_records %}
  <div class="card">
    <p><strong>日付：</strong> {{ record.date }}</p>
    <p><strong>カテゴリ：</strong> {{ record.category.name }}</p>
    <p><strong>難易度：</strong> {{ record.get_cooking_easiness_display }}</p>
    <p><strong>お気に入り：</strong> {{ record.is_favorite|yesno:"★,-" }}</p>
    <p><strong>メモ：</strong> {{ record.memo }}</p>
    {% if record.image_url %}
      <img src="{{ record.image_url.url }}" alt="料理画像" width="200">
    {% endif %}
  </div>
{% empty %}
  <p>記録はまだありません。</p>
{% endfor %}

{% endblock  %}

cooking_memory/cooking_memory_app/login_view/templates/mypage.html
{% extends 'base.html' %}

{% block title %}マイページ{% endblock %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/sanitize.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<style>
  .main-content {
    margin-top: 100px; /* ヘッダーの高さ分だけ空ける */
  }

  h1 {
    font-size: 60px;
    text-align: center;
  }

  img{
    width: 50%;
  }

  form div {
    font-size: 40px;
    margin-bottom: 80px;
    width: 100%;
    max-width: 700px; /* 入力欄の幅を制限 */
  }
  div {
    font-size: 40px;
  }
  label {
    display: block;
    font-size: 60px;
  }
  input[type="submit"] {
    font-size: 50px;
    padding: 10px 30px;
  }
  .user-name {
    text-align: center;
    margin-top: 60px;
    font-size: 60px;
    font-weight: bold;
  }
  .mypage-list {
    margin-top: 50px;
  }
  .mypage-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 50px;
    padding: 20px;
    border-bottom: 1px solid #ccc;
  }
  .menu-link,
  .arrow {
    color: black;
    text-decoration: none; /* 下線消したい場合 */
  }
  #nameChangeModal {
    font-size: 40px;
    color: gray;
    margin-left: 10px;
    text-decoration: none;
  }

  {% comment %} .menu-link {
    display: inline-block;        /* 横幅と高さを指定できる行内要素に */
    padding: 5px 5px;           /* 上下に px、左右に pxの余白 */
    color: #333;                  /* 文字の色（#333はダークグレー） */
    margin-top: 50px;             /* 上に50pxの余白（離す） */
    } {% endcomment %}

</style>

<div class="main-content">
  {% comment %} <h1>マイページ</h1> {% endcomment %}
  <!-- プロフィール画像 -->
  {% if user.image_url %}
    <div style="text-align: center;"><img src="{{ user.image_url.url }}" alt="プロフィール画像"></div>
  {% else %}
    <p style="text-align: center;">画像がありません</p>
  {% endif %}

  <form method="post" enctype="multipart/form-data" action="{% url 'accounts:upload_profile_image' %}">
    {% csrf_token %}
    <a style="font-size: 40px; text-align: center;"><input type="file" name="image"></a>
    <button type="submit" style="font-size: 50px; margin-top: 10px;">選択した画像を登録</button>
  </form>

  <!-- 名前/ニックネーム -->
  <div class="user-name">
    {{ user.username }}<button data-bs-toggle="modal" data-bs-target="#nameChangeModal" style="font-size: 50px; margin-left:20px">名前変更</button>
  </div>

  <ul class="mypage-list">
    <div class="mypage-item">
      <a class="menu-link" href="{% url 'accounts:change_email' %}">メールアドレス変更</a>
      <a href="{% url 'accounts:change_email' %}" target="_blank" class="arrow">＞</a>
    </div>
    <div class="mypage-item">
      <a class="menu-link" href="{% url 'accounts:change_password' %}">パスワード変更</a>
      <a href="{% url 'accounts:change_password' %}" target="_blank" class="arrow">＞</a>
    </div>
    <div class="mypage-item">
      <a class="menu-link" href="{% url 'accounts:generate_invite' %}">招待用URLの発行</a>
      <a href="{% url 'accounts:generate_invite' %}" target="_blank" class="arrow">＞</a>
    </div>
    <div class="mypage-item">
      <a class="menu-link" href="#" data-bs-toggle="modal" data-bs-target="#shareUsersModal" onclick="share_users()">共有中のユーザー</a>
      <a href="#" data-bs-toggle="modal" data-bs-target="#shareUsersModal" onclick="share_users()" target="_blank" class="arrow">＞</a>
    </div>
  </ul>

  <!-- ログアウト -->
  <form method="post" action="{% url 'accounts:user_logout_2' %}">
    {% csrf_token %}
    <button style="font-size: 60px; background-color: red; color: white;">ログアウト</button>
  </form>
</div>


<!-- モーダル本体 -->
<div class="modal fade" id="nameChangeModal" tabindex="-1" aria-labelledby="nameChangeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{% url 'accounts:change_username' %}">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="nameChangeModalLabel">名前/ニックネーム</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
        </div>
        <div class="modal-body">
          <input type="text" name="username" value="{{ user.username }}" class="form-control">
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" style="font-size: 40px;">変更</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="shareUsersModal" tabindex="-1" aria-labelledby="shareUsersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="shareUsersModalLabel">共有中のユーザー</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
        </div>
        <div class="modal-body">
          <!-- ここに共有ユーザーのリストを表示 -->
          <ul id="shareUsersList"></ul>
        </div>
      </div>
    </div>
  </div>


<script>
  function share_users() {
      fetch("{% url 'accounts:share_users' %}")
          .then(response => response.json())
          .then(data => {
              const userListDiv = document.getElementById("shareUsersList");
              userListDiv.innerHTML = "";// 既存のリストをクリア

              if (data.users.length > 0) {                  
                  data.users.forEach(user => {
                    const li = document.createElement("li");
                    li.textContent = user.name;
                    userListDiv.appendChild(li);
               });
              } else {
                  userListDiv.innerHTML = "<p>共有中のユーザーはいません。</p>";
              }
          })
          .catch(error => {
              document.getElementById("shareUsersList").innerHTML = "<p>読み込みに失敗しました。</p>";
              console.error("エラー:", error);
          });
  }
  </script>

{% endblock %}

cooking_memory/cooking_memory_app/login_view/templates/regist.html
{% block content %}
<style>
    h1 {
        color: #F58220;
        font-size: 100px;
        font-weight: bold;
        font-family: fantasy;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center; /* 子要素（入力欄・ボタン）を中央に */
        margin-top: 0%;
    }
    
    form div {
        margin-bottom: 50px;
        width: 100%;
        max-width: 700px; /* 入力欄の幅を制限 */
    }
    label {
        display: block;
        font-size: 60px;
    }
    input[type="text"],
    input[type="email"],
    input[type="password"]{
      font-size: 60px;
      height: 100px;
    }
    input[type="submit"] {
        font-size: 60px;
        padding: 10px 30px;
    }
    .back-to-login {
        display: inline-block;        /* 横幅と高さを指定できる行内要素に */
        font-size: 40px;              /* 文字の大きさ */
        padding: 15px 30px;           /* 上下に15px、左右に30pxの余白 */
        color: #333;                  /* 文字の色（#333はダークグレー） */
        margin-top: 50px;             /* 上に50pxの余白（離す） */
      }

</style>  

<form method="POST">
    {% csrf_token %}
    <h1>くくめも</h1>

    {% if form.errors %}
        <div class="form-errors" style="color: red; font-size: 2em;">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div>
        {{ form.username.label_tag }}<br>
        {{ form.username }}
    </div>
    <div>
        {{ form.email.label_tag }}<br>
        {{ form.email }}
    </div>
    <div>
        {{ form.password.label_tag }}<br>
        {{ form.password }}
    </div>
    <div>
        {{ form.password2.label_tag }}<br>
        {{ form.password2 }}
    </div>
    <input type="submit" value="登録">
    
    <a href="{% url 'accounts:user_login_2' %}" class="back-to-login">ログイン画面へ戻る</a>
</form>
{% endblock  %}

cooking_memory/cooking_memory_app/login_view/templates/user_logout.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="ログアウト">
</form>
{% endblock  %}