cooking_memory/cooking_memory/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cooking_memory/cooking_memory_app/login_view/accounts/urls.py
from django.urls import path
from .views import(
    PortfolioView,RegistUserView,
    UserLogoutView,UserLoginView2,
    UserLogoutView2,ChangeEmailView,MyPasswordChangeView,
    MyPageView,GenerateInviteView,InviteRegistUserView,
    ShareUsersView,UploadProfileImageView, ChangeUsernameView,
    
)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',PortfolioView.as_view(),name='portfolio'),
]

app_name='accounts'
urlpatterns = [
    path('regist/',RegistUserView.as_view(),name='regist'),
    path('user_logout/',UserLogoutView.as_view(),name='user_logout'),
    path('user_login2/',UserLoginView2.as_view(),name='user_login_2'),
    path('user_logout2/',UserLogoutView2.as_view(),name='user_logout_2'),
    path('change_email/',ChangeEmailView.as_view(),name='change_email'),
    path('change_password/',MyPasswordChangeView.as_view(),name='change_password'),
    path('mypage/', MyPageView.as_view(), name='mypage'),
    path('generate_invite/',GenerateInviteView.as_view(),name='generate_invite'),
    path('share_regist/<str:invitation_url>/', InviteRegistUserView.as_view(), name='share_regist'),
    path('share_users/', ShareUsersView.as_view(), name='share_users'),
    path('upload_profile_image/', UploadProfileImageView.as_view(), name='upload_profile_image'),
    path('change_username/', ChangeUsernameView.as_view(), name='change_username'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/cooking_records/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import(
    MyListView,CookingRecordCreateView,CreateCookingCategoryView,
    CreateToggleFavoriteView,CookingRecordDetailView,
    CookingRecordDeleteView,CookingRecordUpdateView,ToggleFavoriteView
)
from . import views

app_name='cooking_records'
urlpatterns = [
    path('my_list/',MyListView.as_view(),name='my_list'),
    path('create/', CookingRecordCreateView.as_view(), name='cooking_record_create'),
    path('create_category/', CreateCookingCategoryView.as_view(), name='create_cooking_category'),
    path('create_toggle_favorite/', CreateToggleFavoriteView.as_view(), name='create_toggle_favorite'),
    path('record_detail/<int:pk>/', CookingRecordDetailView.as_view(), name='record_detail'),
    path('cooking_record/<int:pk>/delete/', CookingRecordDeleteView.as_view(), name='cooking_record_delete'),
    path('<int:pk>/update/', CookingRecordUpdateView.as_view(), name='cooking_record_update'),
    path('<int:pk>/toggle_favorite/', ToggleFavoriteView.as_view(), name='toggle_favorite'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/login_view/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from login_view.views import PortfolioView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PortfolioView.as_view(), name='portfolio'),  # ← トップページに設定
    path('accounts/', include('accounts.urls')),
    path('cooking_records/', include('cooking_records.urls')),
    path('recipes/', include('recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cooking_memory/cooking_memory_app/login_view/recipes/urls.py
from django.urls import path
from .views import RecipeListView,RecipeCreateView,RecipeDeleteView

app_name='recipes'
urlpatterns = [
    path('recipe_list/',RecipeListView.as_view(),name='recipe_list'),
    path('add_recipe/',RecipeCreateView.as_view(),name='add_recipe'),
    path('recipe/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),

]

cooking_memory/cooking_memory_app/login_view/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import(
    TemplateView,CreateView,FormView,View
)
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash,get_user_model
from .forms import RegistForm,UserLoginForm,UserLoginForm2,EmailChangeForm,PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib import messages
from django.utils.crypto import get_random_string
from .models import Invitation,ShareGroup,User
from django.http import JsonResponse,Http404
from django.views import View
from django.views.generic.edit import FormView

User = get_user_model()

class PortfolioView(TemplateView):
    template_name='portfolio.html'
    
class RegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm
    success_url = reverse_lazy('cooking_records:my_list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()

        # ここでログイン処理
        user = authenticate(self.request, email=user.email, password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            print("認証失敗")
            
        return super().form_valid(form)
    
class UserLoginView2(FormView):
    template_name='user_login_2.html'
    form_class=UserLoginForm2
    success_url = reverse_lazy('cooking_records:my_list')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(self.request, email=email, password=password)
        if user:
            login(self.request, user)
            return super().form_valid(form)
        else:
            messages.error(self.request, "メールアドレスまたはパスワードが正しくありません。")
            return self.form_invalid(form)
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        print('next: ', next_url)
        return next_url if next_url else self.success_url

class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'user_logout.html')

    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect('cooking_records:my_list')
    
class UserLogoutView2(LogoutView):
    next_page = reverse_lazy('cooking_records:my_list')
    http_method_names = ['get', 'post']
    template_name = 'user_logout.html'   
    
class ChangeEmailView(LoginRequiredMixin,FormView):
    template_name='change_email.html'
    form_class=EmailChangeForm
    success_url = reverse_lazy('accounts:mypage')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ←ここで渡す
        return kwargs
    
    def form_valid(self, form):
        user = self.request.user
        user.email = form.cleaned_data['new_email']
        user.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        print('next: ', next_url)
        return next_url if next_url else self.success_url

class MyPasswordChangeView(LoginRequiredMixin, FormView):
    template_name='change_password.html'
    form_class=PasswordChangeForm
    success_url = reverse_lazy('accounts:mypage')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ←ここで渡す
        return kwargs
    
    def form_valid(self, form):
        new_password = form.cleaned_data['new_password']
        user = self.request.user
        user.set_password(new_password)
        user.save()
        update_session_auth_hash(self.request, user)  # ← これでログアウトされないように！
        return super().form_valid(form)
    

class MyPageView(LoginRequiredMixin, TemplateView):
    template_name = 'mypage.html'
        
class GenerateInviteView(LoginRequiredMixin, TemplateView):
    template_name = 'generate_invite.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        token = get_random_string(20)
        
        # フルURLはcontextに渡すだけ
        invite_url = self.request.build_absolute_uri(
            reverse('accounts:share_regist', args=[token])
        )
        
        # invitation_urlにはtokenだけ保存
        Invitation.objects.create(
            user=self.request.user,
            invitation_url=token,
            used=0  # 0: 未使用
        )
            
        context['invite_url'] = invite_url
        return context
    
class InviteRegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm
    success_url = reverse_lazy('cooking_records:my_list')

    def dispatch(self, request, *args, **kwargs):
        self.invitation_url = kwargs.get('invitation_url')  # 招待URLの取得
        try:
            self.invitation = Invitation.objects.get(invitation_url=self.invitation_url, used=0)
        except Invitation.DoesNotExist:
            raise Http404("この招待URLは無効か、すでに使用されています。")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        # 招待者を取得
        inviter = self.invitation.user
        # 招待者がshare_groupを持っていなければ作成
        if not inviter.share_group:
            group = ShareGroup.objects.create()
            inviter.share_group = group
            inviter.save()
        else:
            group = inviter.share_group

        # 招待されたユーザーにもグループを割り当て
        user.share_group = group
        user.is_active = True
        user.save()

        # 招待トークンを使用済みにする
        self.invitation.used = 1
        self.invitation.save()

        # ここでログイン処理
        user = authenticate(self.request, email=user.email, password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            print("認証失敗")
            
        return super().form_valid(form)

class ShareUsersView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            print("ログインユーザー：", request.user)
            print("ユーザーのグループ：", request.user.share_group)
            
            share_group = request.user.share_group
            
            if share_group is None:
                # 共有グループに属していなければ空リストを返す
                return JsonResponse({'users': []})
        
            users = User.objects.filter(share_group=share_group).exclude(id=request.user.id)
            
            print("共有中ユーザー：", users)
            
            data = {
                'users': [{'name': user.username} for user in users]
            }
        except Exception as e:
            print("エラー内容：", str(e))
            
            data = {
                'error': str(e)
            }

        return JsonResponse(data)
    
class UploadProfileImageView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        
        if 'image' in request.FILES:
            user.image_url = request.FILES['image']
            user.save()
        return redirect('accounts:mypage')
    
class ChangeUsernameView(LoginRequiredMixin, View):
    def post(self, request):
        new_username = request.POST.get('username')
        if new_username:
            request.user.username = new_username
            request.user.save()
        return redirect('accounts:mypage')

cooking_memory/cooking_memory_app/login_view/cooking_records/views.py
from django.views import View
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import(
    ListView,CreateView,DetailView,DeleteView,UpdateView
)
from django.urls import reverse_lazy
from django.db.models import Q
from .models import CookingRecord,CookingCategory,CookingRecordRecipe,Recipe
from .forms import CookingRecordForm
import json


class MyListView(LoginRequiredMixin, ListView):
    model = CookingRecord
    template_name = 'cooking_records/my_list.html'
    context_object_name = 'cooking_records'

    def get_queryset(self):
        if self.request.user.share_group:
            cooking_records = CookingRecord.objects.filter(
                Q(user__share_group=self.request.user.share_group) |
                Q(user=self.request.user)
            ).distinct()
        else:
            cooking_records = CookingRecord.objects.filter(user=self.request.user)
        return cooking_records.order_by('-date')
    
class CookingRecordCreateView(LoginRequiredMixin, CreateView):
    model = CookingRecord
    form_class = CookingRecordForm
    template_name = 'cooking_records/record_form.html'
    success_url = reverse_lazy('cooking_records:my_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ここでフォームにuserを渡す
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        share_group_id = self.request.user.share_group_id
        context['recipes'] = Recipe.objects.filter(user__share_group_id=share_group_id).order_by('-created_at')
        return context

    def form_valid(self, form):
        print(self.request.POST)
        form.instance.user = self.request.user  # ユーザーを紐づける
        
        # hidden inputから is_favorite も取得してセット
        is_favorite = self.request.POST.get('is_favorite', '0')
        form.instance.is_favorite = int(is_favorite)
        
        response = super().form_valid(form)

        # hidden input からレシピIDを取得
        recipe_ids = self.request.POST.getlist('recipes')
        for rid in recipe_ids:
            if rid:  # 念のため空チェック
                CookingRecordRecipe.objects.create(
                    cooking_record=self.object,  # 作ったばかりのレコード
                    recipe_id=rid
                )
        return response
    
class CreateToggleFavoriteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
            try:
                # リクエストボディの取得
                data = json.loads(request.body)

                # レコードIDとお気に入り状態の取得
                record_id = data.get('record_id')
                is_favorite = data.get('is_favorite')
                
                if record_id is None or is_favorite is None:
                    return JsonResponse({'error': 'Invalid data'}, status=400)
                
                record = CookingRecord.objects.get(id=record_id, user=request.user)
                record.is_favorite = is_favorite
                record.save()
                
                return JsonResponse({'is_favorite': record.is_favorite})
            
            except CookingRecord.DoesNotExist:
                return JsonResponse({'error': 'Record not found'}, status=404)
            except json.JSONDecodeError:
                return JsonResponse({'error': 'Invalid request'}, status=400)
    
class CreateCookingCategoryView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        name = data.get("name")
        if name:
            category = CookingCategory.objects.create(user=request.user, name=name)
            return JsonResponse({"success": True, "id": category.id, "name": category.name})
        return JsonResponse({"success": False}, status=400)
        
class CookingRecordDetailView(DetailView):
    model = CookingRecord
    template_name = 'cooking_records/record_detail.html'
    context_object_name = 'record'# テンプレートで使う変数名（record）
    
class CookingRecordDeleteView(DeleteView):
    model = CookingRecord
    template_name = 'cooking_record_confirm_delete.html'  # 使わないけど書く
    success_url = reverse_lazy('cooking_records:my_list')
    
class CookingRecordUpdateView(LoginRequiredMixin, UpdateView):
    model = CookingRecord
    form_class = CookingRecordForm
    template_name = 'cooking_records/record_update_form.html'
    success_url = reverse_lazy('cooking_records:my_list')
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ここでフォームにuserを渡す
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        share_group_id = self.request.user.share_group_id
        context['recipes'] = Recipe.objects.filter(user__share_group_id=share_group_id).order_by('-created_at')
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)

        # いったん既存の関連を全部削除
        CookingRecordRecipe.objects.filter(cooking_record=self.object).delete()

        # 新しくレシピを紐づけ直す
        recipe_ids = self.request.POST.getlist('recipes')
        for rid in recipe_ids:
            if rid:  # 念のため空チェック
                CookingRecordRecipe.objects.create(
                    cooking_record=self.object,
                    recipe_id=rid
                )
        return response

    
class ToggleFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        record = get_object_or_404(CookingRecord, pk=pk, user=request.user)
        record.is_favorite = not record.is_favorite  # 現在の値を反転
        record.save()
        return JsonResponse({'is_favorite': record.is_favorite})

cooking_memory/cooking_memory_app/login_view/templates/cooking_records/cooking_record_delete.html
/* ダミー */

cooking_memory/cooking_memory_app/login_view/templates/cooking_records/my_list.html
{% extends 'base.html' %}
{% block content %}

<style>
  .main-content {
    margin-top: 100px; /* ヘッダーの高さ分だけ空ける */
  }

  .record-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); /* 横に最大3枚 */
    gap: 5px;
    padding: 5px;
    justify-items: center;
  }
  
  .record img {
    width: 100%;
    height: auto;
    max-width: 300px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
  }
  
  .record {
    text-align: center;
  }

  .image-container {
    position: relative;
    width: 100%;
    max-width: 300px;
    {% comment %} aspect-ratio: 5 / 3; /* 横長にする */ {% endcomment %}
    aspect-ratio: 1 / 1; /* 正方形にする */
    overflow: hidden;     /* はみ出た部分を隠す */
    border: 5px solid black; /* 黒枠をつける */
  }
  
  .image-container img {
    width: 100%;
    height: 100%;
    object-fit: cover; /* 中央を基準にトリミング（切り抜き） */
    object-position: center;
    display: block;
  }
  
  .image-link-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1; /* ハートボタンより下 */
  }
  
  .favorite-btn {
    position: absolute;
    top: 0px;
    right: 0px;
    font-size: 100px;
    background: none;
    border: none;
    cursor: pointer;
    z-index: 2;
    margin: 0;
  }

  {% comment %} @media (max-width: 768px) {
    .favorite-btn {
      position: absolute;
      top: 0px;
      right: 0px;
      font-size: 80px;
      background: none;
      border: none;
      cursor: pointer;
      z-index: 2;
      }
  }  
 {% endcomment %}

  .floating-plus-btn {
    position: fixed;
    bottom: 60px;
    right: 60px;
    background-color: #e0e0e0;
    color: #000000;
    font-size: 100px;
    border-radius: 50%;
    width: 150px;
    height: 150px;
    text-align: center;
    line-height: 150px;
    text-decoration: none;
    box-shadow: 0 4px 8px rgba(0,0,0,0.3);
    transition: background-color 0.3s;
    z-index: 1000;
  }
  
</style>

<div class="main-content">
  {% if cooking_records %}
    <div class="record-grid">
      {% for record in cooking_records %}
        <div class="record">
          <div class="image-container">
            {% if record.image_url %}
              <img src="{{ record.image_url.url }}" alt="料理写真" />
              <a href="{% url 'cooking_records:record_detail' record.id %}" class="image-link-overlay"></a>
              <button class="favorite-btn" onclick="toggleFavorite({{ record.id }}, this)">
                {% if record.is_favorite %}
                  ❤️
                {% else %}
                  🤍
                {% endif %}
              </button>
      
            {% else %}
                <p>画像なし</p>
                {% comment %} <img src="{% static 'images/no_image.png' %}" alt="画像なし" /> {% endcomment %}
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div style="font-size:40px; "><br>　まだ登録はありません。<br>　下の＋ボタンから料理を登録して下さい。</div>    
    {% endif %}
  </div>

<script>
  function toggleFavorite(recordId, btn) {
    fetch(`/cooking_records/${recordId}/toggle_favorite/`, {
      method: 'POST',
      headers: {
        'X-CSRFToken': '{{ csrf_token }}',
        'Content-Type': 'application/json'
      },
    })
    .then(res => res.json())
    .then(data => {
      btn.textContent = data.is_favorite ? '❤️' : '🤍';
    });
  }
</script>

<a href="{% url 'cooking_records:cooking_record_create' %}" class="floating-plus-btn">＋</a>

{% endblock  %}

cooking_memory/cooking_memory_app/login_view/templates/cooking_records/record_detail.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/sanitize.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<style>
  .main-content {
    margin-top: 100px; /* ヘッダーの高さ分だけ空ける */
  }

  .content {
    padding-left: 30px; /* 左側に30pxの余白 */
    padding-right: 30px; /* 右側に30pxの余白 */
  }

  .image-container{
    font-size: 30px;
  }

  .easiness-labels {
    margin-top: 5px;
    font-size: 30px;
    text-align: left;
  }

  .favorite-icon {
    position: absolute;
    top: 10px;
    right: 20px;
    font-size: 100px;
    background: none;
    border: none
    text-decoration: none;
  }
  
  .recipe-list {
    font-size: 40px !important;
    color: #000000 !important;
    text-decoration: none !important;
  }

  .update-btn {
    display: block;
    margin-left: auto;  /* 左側の余白を自動にして右寄せ */
    margin-right: 10px; /* 右端との間隔 */
    margin-bottom: 40px; /* 下との感覚 */
    color: blue;
    font-size: 40px;
    background: none;
    border: none;
    cursor: pointer;
    }

  #deleteBtn {
    background-color: red;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    text-align: center;
    display: block;      /* ブロック要素にする */
    margin: 0 auto;      /* 左右中央に配置 */
  }

  #deleteModal {
    display: none;
    position: fixed;
    font-size: 40px;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0,0,0,0.5);
  }

  .confirm-btn {
    flex: 1;
    padding: 10px 0;
    border: none;
    border-radius: 5px;
    font-size: 40px;
    width: 200px;
    cursor: pointer;
  }

</style>

<div class="main-content">
  <div class="image-container" style="position: relative;">
    <img src="{{ record.image_url.url }}" alt="料理写真" style="width: 100%; height: auto;">
    <a class="favorite-icon" style="text-decoration: none;">  
      {% if record.is_favorite %}
        ❤️
      {% else %}
        🤍
      {% endif %}
    </a>
  </div>

  <div class="content">
    <div style="text-align: right;">
      <a href="{% url 'cooking_records:cooking_record_update' pk=record.pk %}" class="update-btn" style="font-size: 3.5em;">
        編集
      </a>
    </div>
    <div class="form-group">
      {% comment %} <table>
        <tr>
          <th>日付：</th>
          <td>{{ record.date|date:"Y/n/j" }}</td>
        </tr>
        <tr>
          <th>カテゴリ：</th>
          <td>{{ record.cooking_category.name }}</td>
        </tr>
        <tr>
          <th>調理の手軽さ：</th>
          <td>{% if record.cooking_easiness == 0 %}😊
              {% elif record.cooking_easiness == 1 %}🙂
              {% else %}😣
              {% endif %}
          </td>
        </tr>
        <tr>
          <th>メモ：</th>
          <td>{{ record.memo|linebreaksbr }}</td>
        </tr>
        <tr>
          <th>参考レシピ：</th>
          <td>
            {% for cr_recipe in record.cooking_record_recipes.all %}
            <a href="{{ cr_recipe.recipe.recipe_url }}" target="_blank" style="font-size: 1.5em;">{{ cr_recipe.recipe.name }}</a><br>
            {% endfor %}
          </td>
        </tr>
      </table> {% endcomment %}

      <p>【日付】{{ record.date|date:"Y/n/j" }}</p>
      <p>【カテゴリ】{{ record.cooking_category.name }}</p>
      <p>【調理の手軽さ】
        {% if record.cooking_easiness == 0 %}😊
        {% elif record.cooking_easiness == 1 %}🙂
        {% else %}😣
        {% endif %}
      </p>

      <label>【メモ】</label>
      <p style="padding-left: 25px;">{{ record.memo|linebreaksbr }}</p>

      <div>
        <label>【参考レシピ】</label>
        <div class="recipe-list">
          {% for cr_recipe in record.cooking_record_recipes.all %}
            <a href="{{ cr_recipe.recipe.recipe_url }}" target="_blank" style="font-size: 1.5em; padding-left: 25px;">{{ cr_recipe.recipe.name }}</a><br>
          {% endfor %}
        </div>
      </div>
      <button id="deleteBtn">削除</button>
    </div>
  </div>

<!-- モーダル -->
<div id="deleteModal">
  <div style="background: white; padding: 20px; margin: 100px auto; width: 50%; border-radius: 8px; text-align: center;">
    <p>この料理メモを削除しますか？</p>
    <form method="POST" action="{% url 'cooking_records:cooking_record_delete' record.pk %}">
      {% csrf_token %}
      <div style="display: flex; justify-content: center; gap: 20px; margin-top: 20px;">
        <button type="submit" class="confirm-btn" style="background-color: red; color: white; padding: 10px 20px; font-size: 40px;">はい</button>
        <button type="button" id="cancelBtn" class="confirm-btn" style="padding: 10px 20px;">いいえ</button>
      </div>
    </form>
  </div>
</div>

<script>
  const deleteBtn = document.getElementById('deleteBtn');
  const deleteModal = document.getElementById('deleteModal');
  const cancelBtn = document.getElementById('cancelBtn');

  deleteBtn.addEventListener('click', function() {
    deleteModal.style.display = 'block';
  });

  cancelBtn.addEventListener('click', function() {
    deleteModal.style.display = 'none';
  });
</script>

{% endblock  %}